; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = atmelavr
lib_deps =
    ; https://github.com/udoklein/dcf77.git
    https://github.com/Servacek/dcf77_xtal.git
    https://github.com/adafruit/RTClib.git
    https://github.com/RobTillaart/INA219.git
framework = arduino
; framework = baremetal

[env:uno]
board = uno

; No verification in debug mode
[env:uno_usbasp_dev]
board = ATmega328P
upload_protocol = usbasp
upload_speed = 115200
build_flags =
    -Wall
    -Wextra
    ; -v
upload_flags =
    -Pusb
    -save-temps
    -e
    ; -v
    -fstack-usage
    -V ; No verification in debug mode

[env:uno_usbasp_prod]
board = uno
upload_protocol = usbasp
upload_flags =
    -Pusb
    -e

[env:unoasm]
board = uno
build_flags =
  -save-temps=obj
  -fverbose-asm


[env:oldnano]
board = nanoatmega328
upload_flags =
    -e
    -V ; No verification in debug mode

[env:nano]
board = nanoatmega328new
